<?php
echo '<!DOCTYPE html>';
echo '<html>';
echo '<head>';
echo '<meta charset="utf-8" />';
echo '<link rel="icon" href="/favicon.ico" />';
echo '<meta name="viewport" content="width=device-width, initial-scale=1" />';
echo '<meta name="theme-color" content="#000000" />';
echo '<title>Desktop - 2</title>';
echo '<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Inter%3A400"/>';
echo '<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro%3A400"/>';
echo '<link rel="stylesheet" href="./styles/desktop-2.css"/>';
echo '</head>';
echo '<body>';
echo '<div class="desktop-2-iMb">';
echo '<div class="desktop-1-G8D">';
echo '<div class="auto-group-y4bo-cSy">';
echo '<div class="rectangle-1-Z7K">';
echo '</div>';
echo '<p class="hotel-management-system-Jah">HOTEL MANAGEMENT SYSTEM</p>';
echo '<div class="rectangle-6-CRB">';
echo '</div>';
echo '<p class="function-list-YE9">';
echo 'Function';
echo '<br/>';
echo 'list';
echo '</p>';
echo '<p class="employee-info-EMs">';
echo 'Employee';
echo '<br/>';
echo 'Info';
echo '</p>';
echo '<p class="management-i29">Management</p>';
echo '<p class="reserve-and-checkout-d97">';
echo 'Reserve';
echo '<br/>';
echo 'and';
echo '<br/>';
echo 'Checkout';
echo '</p>';
echo '<p class="room-info-management-YG5">';
echo 'Room';
echo '<br/>';
echo 'Info';
echo '<br/>';
echo 'Management';
echo '</p>';
echo '<p class="customer-info-query-FRP">';
echo 'Customer';
echo '<br/>';
echo 'Info';
echo '<br/>';
echo 'Query';
echo '</p>';
echo '<p class="change-password-xqb">';
echo 'Change';
echo '<br/>';
echo 'Password';
echo '</p>';
echo '</div>';
echo '<div class="auto-group-5jrq-eTX">';
echo '<div class="auto-group-hbpq-8tV">Layout</div>';
echo '<div class="auto-group-dsbs-yeD">Room Management System</div>';
echo '<div class="auto-group-az4h-DHf">';
echo '<p class="room-number--KLh">Room Number:</p>';
echo '<div class="rectangle-8-EiZ">';
echo '</div>';
echo '<div class="auto-group-tdqf-itd">search</div>';
echo '</div>';
echo '<div class="auto-group-ytjv-vzh">';
echo '<img class="rectangle-5-RRf" src="./assets/rectangle-5-KMF.png"/>';
echo '<p class="room-type--9cZ">Room Type:</p>';
echo '<div class="rectangle-9-3C9">';
echo '</div>';
echo '<div class="rectangle-11-x4D">';
echo '</div>';
echo '<p class="v-rfP">v</p>';
echo '<p class="search-XmX">search</p>';
echo '<div class="rectangle-12-ER3">';
echo '</div>';
echo '<p class="delete-jsb">Delete</p>';
echo '<p class="room-type-THo">';
echo 'Room';
echo '<br/>';
echo 'Type';
echo '</p>';
echo '<img class="line-1-mZP" src="./assets/line-1-Xiu.png"/>';
echo '<img class="line-2-WG5" src="./assets/line-2.png"/>';
echo '<img class="line-3-qp9" src="REPLACE_IMAGE:6:37"/>';
echo '<img class="line-4-njP" src="./assets/line-4.png"/>';
echo '<img class="line-5-8YM" src="./assets/line-5.png"/>';
echo '<img class="line-6-eFo" src="./assets/line-6.png"/>';
echo '<img class="line-7-yJ5" src="./assets/line-7.png"/>';
echo '<img class="line-8-JbF" src="./assets/line-8.png"/>';
echo '<p class="room-number-TDF">';
echo 'Room';
echo '<br/>';
echo 'Number';
echo '</p>';
echo '<p class="room-price-yBb">';
echo 'Room';
echo '<br/>';
echo 'Price';
echo '</p>';
echo '<p class="room-details-6GD">';
echo 'Room';
echo '<br/>';
echo 'Details';
echo '</p>';
echo '<p class="modify-neq">Modify</p>';
echo '<p class="delete-hmo">Delete</p>';
echo '<p class="detail-QRK">Detail</p>';
echo '<p class="detail-gtd">Detail</p>';
echo '<p class="delete-cGV">Delete</p>';
echo '<img class="line-9-8Vj" src="./assets/line-9.png"/>';
echo '<img class="line-10-fEm" src="./assets/line-10.png"/>';
echo '<img class="line-11-13j" src="./assets/line-11.png"/>';
echo '<div class="line-12-k1K">';
echo '</div>';
echo '<p class="room-page-Ui1">Room Page</p>';
echo '<div class="line-13-nyb">';
echo '</div>';
echo '<img class="vector-1-tmj" src="./assets/vector-1.png"/>';
echo '<img class="vector-2-QVB" src="./assets/vector-2.png"/>';
echo '<img class="vector-3-8g5" src="./assets/vector-3.png"/>';
echo '<img class="vector-4-GnH" src="./assets/vector-4.png"/>';
echo '<img class="vector-5-Pc1" src="./assets/vector-5.png"/>';
echo '<img class="vector-6-vM3" src="./assets/vector-6.png"/>';
echo '<img class="vector-7-F8R" src="./assets/vector-7.png"/>';
echo '</div>';
echo '<div class="auto-group-ezlm-aAh">Add Room</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</body>';
?>