<?php
echo '<!DOCTYPE html>';
echo '<html>';
echo '<head>';
echo '<meta charset="utf-8" />';
echo '<link rel="icon" href="/favicon.ico" />';
echo '<meta name="viewport" content="width=device-width, initial-scale=1" />';
echo '<meta name="theme-color" content="#000000" />';
echo '<title>Desktop - 5</title>';
echo '<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Inter%3A400"/>';
echo '<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro%3A400"/>';
echo '<link rel="stylesheet" href="./styles/desktop-5.css"/>';
echo '</head>';
echo '<body>';
echo '<div class="desktop-5-jX3">';
echo '<div class="desktop-1-H2m">';
echo '<div class="desktop-1-Eyb">';
echo '<div class="auto-group-lxdf-zhs">';
echo '<div class="rectangle-1-jfT">';
echo '</div>';
echo '<p class="hotel-management-system-5UR">HOTEL MANAGEMENT SYSTEM</p>';
echo '<div class="rectangle-6-BXT">';
echo '</div>';
echo '<p class="function-list-UWZ">';
echo 'Function';
echo '<br/>';
echo 'list';
echo '</p>';
echo '<p class="employee-info-wQ9">';
echo 'Employee';
echo '<br/>';
echo 'Info';
echo '</p>';
echo '<p class="management-Eu3">Management</p>';
echo '<p class="reserve-and-checkout-Yeq">';
echo 'Reserve';
echo '<br/>';
echo 'and';
echo '<br/>';
echo 'Checkout';
echo '</p>';
echo '<p class="room-info-management-r9j">';
echo 'Room';
echo '<br/>';
echo 'Info';
echo '<br/>';
echo 'Management';
echo '</p>';
echo '<p class="customer-info-query-MMP">';
echo 'Customer';
echo '<br/>';
echo 'Info';
echo '<br/>';
echo 'Query';
echo '</p>';
echo '<p class="change-password-1gq">';
echo 'Change';
echo '<br/>';
echo 'Password';
echo '</p>';
echo '</div>';
echo '<p class="layout-hJm">Layout</p>';
echo '<div class="auto-group-5rsh-2rq">';
echo '<div class="auto-group-gn9b-knq">Reservation</div>';
echo '<div class="auto-group-ygaz-RPB">';
echo '<div class="auto-group-4wwb-xe1">';
echo '<img class="rectangle-5-9Ch" src="./assets/rectangle-5-XeV.png"/>';
echo '<div class="rectangle-8-3Yy">';
echo '</div>';
echo '<p class="room-number-customer-name-phone-number-e-mail-current-time-note--BfB">';
echo 'Room Number:';
echo '<br/>';
echo 'Customer Name:';
echo '<br/>';
echo 'Phone Number:';
echo '<br/>';
echo 'E-mail:';
echo '<br/>';
echo 'Current Time:';
echo '<br/>';
echo 'Note:';
echo '</p>';
echo '</div>';
echo '</div>';
echo '<div class="auto-group-3f6u-FQ9">';
echo '<div class="auto-group-wbft-AGD">';
echo '<p class="return-V3b">Return</p>';
echo '<img class="line-1-aqj" src="./assets/line-1-nNh.png"/>';
echo '</div>';
echo '<div class="auto-group-cmed-hvM">Checkout</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</body>';
?>