<?php
echo '<!DOCTYPE html>';
echo '<html>';
echo '<head>';
echo '<meta charset="utf-8" />';
echo '<link rel="icon" href="/favicon.ico" />';
echo '<meta name="viewport" content="width=device-width, initial-scale=1" />';
echo '<meta name="theme-color" content="#000000" />';
echo '<title>Desktop - 1</title>';
echo '<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Inter%3A400"/>';
echo '<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro%3A400"/>';
echo '<link rel="stylesheet" href="./styles/desktop-1.css"/>';
echo '</head>';
echo '<body>';
echo '<div class="desktop-1-Z7T">';
echo '<div class="desktop-1-x9b">';
echo '<div class="auto-group-b1u7-Fnu">';
echo '<div class="rectangle-1-yyo">';
echo '</div>';
echo '<p class="hotel-management-system-Uff">HOTEL MANAGEMENT SYSTEM</p>';
echo '<div class="rectangle-6-GrR">';
echo '</div>';
echo '<p class="function-list-13K">';
echo 'Function';
echo '<br/>';
echo 'list';
echo '</p>';
echo '<p class="employee-info-WEy">';
echo 'Employee';
echo '<br/>';
echo 'Info';
echo '</p>';
echo '<p class="management-DQH">Management</p>';
echo '<p class="reserve-and-checkout-vpV">';
echo 'Reserve';
echo '<br/>';
echo 'and';
echo '<br/>';
echo 'Checkout';
echo '</p>';
echo '<p class="room-info-management-eVb">';
echo 'Room';
echo '<br/>';
echo 'Info';
echo '<br/>';
echo 'Management';
echo '</p>';
echo '<p class="customer-info-query-ZsT">';
echo 'Customer';
echo '<br/>';
echo 'Info';
echo '<br/>';
echo 'Query';
echo '</p>';
echo '<p class="change-password-fvV">';
echo 'Change';
echo '<br/>';
echo 'Password';
echo '</p>';
echo '<div class="rectangle-7-Lmj">';
echo '</div>';
echo '<p class="employee-log-in-please-enter-correct-username-and-password-and-click-login-button-and-enter-to-the-system-tYM">';
echo 'Employee Log In';
echo '<br/>';
echo 'Please enter correct username  and password and click “Login” button and enter to the system';
echo '</p>';
echo '</div>';
echo '<div class="auto-group-lv5x-8Bo">';
echo '<div class="auto-group-jb6d-Rwb">';
echo '<p class="username--APP">';
echo 'Username:';
echo '<br/>';
echo '';
echo '</p>';
echo '<div class="rectangle-10-6H3">';
echo '</div>';
echo '</div>';
echo '<img class="rectangle-5-RKK" src="./assets/rectangle-5-zD3.png"/>';
echo '<div class="auto-group-p4ku-XNM">';
echo '<p class="password--dwB">Password:</p>';
echo '<div class="rectangle-9-ARK">';
echo '</div>';
echo '</div>';
echo '<p class="welcome-to-hotel-management-system-7LZ">Welcome to hotel management system</p>';
echo '<div class="auto-group-8bkj-dJu">';
echo '<p class="your-user-type-is-N1b">Your user type is </p>';
echo '<img class="line-1-gHB" src="./assets/line-1.png"/>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</body>';
?>