<?php
echo '<!DOCTYPE html>';
echo '<html>';
echo '<head>';
echo '<meta charset="utf-8" />';
echo '<link rel="icon" href="/favicon.ico" />';
echo '<meta name="viewport" content="width=device-width, initial-scale=1" />';
echo '<meta name="theme-color" content="#000000" />';
echo '<title>Desktop - 3</title>';
echo '<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Inter%3A400"/>';
echo '<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro%3A400"/>';
echo '<link rel="stylesheet" href="./styles/desktop-3.css"/>';
echo '</head>';
echo '<body>';
echo '<div class="desktop-3-rPf">';
echo '<div class="desktop-1-o41">';
echo '<div class="desktop-1-kzq">';
echo '<div class="auto-group-whdp-hv5">';
echo '<div class="rectangle-1-Rr5">';
echo '</div>';
echo '<p class="hotel-management-system-91P">HOTEL MANAGEMENT SYSTEM</p>';
echo '<div class="rectangle-6-QCD">';
echo '</div>';
echo '<p class="function-list-YJR">';
echo 'Function';
echo '<br/>';
echo 'list';
echo '</p>';
echo '<p class="employee-info-S8u">';
echo 'Employee';
echo '<br/>';
echo 'Info';
echo '</p>';
echo '<p class="management-kfP">Management</p>';
echo '<p class="reserve-and-checkout-sk1">';
echo 'Reserve';
echo '<br/>';
echo 'and';
echo '<br/>';
echo 'Checkout';
echo '</p>';
echo '<p class="room-info-management-z3w">';
echo 'Room';
echo '<br/>';
echo 'Info';
echo '<br/>';
echo 'Management';
echo '</p>';
echo '<p class="customer-info-query-r69">';
echo 'Customer';
echo '<br/>';
echo 'Info';
echo '<br/>';
echo 'Query';
echo '</p>';
echo '<p class="change-password-9qw">';
echo 'Change';
echo '<br/>';
echo 'Password';
echo '</p>';
echo '</div>';
echo '<p class="layout-U7X">Layout</p>';
echo '<div class="auto-group-aqyz-QWy">';
echo '<div class="auto-group-f5tq-jJM">';
echo '<img class="rectangle-5-FGh" src="./assets/rectangle-5-mLy.png"/>';
echo '<div class="rectangle-7-n1j">';
echo '</div>';
echo '<p class="make-reservation-checkout-ykR">Make Reservation /Checkout</p>';
echo '<p class="room-number--5Hf">Room Number:</p>';
echo '<div class="rectangle-8-BrV">';
echo '</div>';
echo '<div class="rectangle-10-8Wq">';
echo '</div>';
echo '<p class="search-Gd3">search</p>';
echo '</div>';
echo '<div class="auto-group-i9do-AiR">';
echo '<p class="room-type--Sfw">Room Type:</p>';
echo '<div class="rectangle-9-kRj">';
echo '</div>';
echo '<div class="auto-group-l2xv-UsX">';
echo '<div class="rectangle-11-dEd">';
echo '</div>';
echo '<p class="search-Zty">search</p>';
echo '</div>';
echo '</div>';
echo '<div class="auto-group-38eq-FWu">';
echo '<div class="rectangle-12-yho">';
echo '</div>';
echo '<p class="price-hdo">Price</p>';
echo '<img class="line-1-NV3" src="./assets/line-1-RiD.png"/>';
echo '<img class="line-2-VZf" src="REPLACE_IMAGE:7:32"/>';
echo '<img class="line-3-RiD" src="./assets/line-3.png"/>';
echo '<img class="line-4-jiu" src="./assets/line-4-WrH.png"/>';
echo '<img class="line-5-qX3" src="./assets/line-5-ogH.png"/>';
echo '<img class="line-6-wpy" src="./assets/line-6-Brm.png"/>';
echo '<p class="room-no-V5o">';
echo 'Room';
echo '<br/>';
echo 'No';
echo '</p>';
echo '<p class="service-mp1">Service</p>';
echo '<p class="room-type-rKf">';
echo 'Room';
echo '<br/>';
echo 'Type';
echo '</p>';
echo '<p class="bed-size-YiH">';
echo 'Bed';
echo '<br/>';
echo 'Size';
echo '</p>';
echo '<p class="area-sEm">Area</p>';
echo '<p class="reserve-checkout-aus">';
echo 'reserve';
echo '<br/>';
echo 'checkout';
echo '<br/>';
echo '';
echo '</p>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</body>';
?>