<?php
echo '<!DOCTYPE html>';
echo '<html>';
echo '<head>';
echo '<meta charset="utf-8" />';
echo '<link rel="icon" href="/favicon.ico" />';
echo '<meta name="viewport" content="width=device-width, initial-scale=1" />';
echo '<meta name="theme-color" content="#000000" />';
echo '<title>Desktop - 4</title>';
echo '<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro%3A400"/>';
echo '<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Inter%3A400"/>';
echo '<link rel="stylesheet" href="./styles/desktop-4.css"/>';
echo '</head>';
echo '<body>';
echo '<div class="desktop-4-bUq">';
echo '<div class="desktop-1-wYh">';
echo '<div class="desktop-1-uVX">';
echo '<div class="auto-group-h3ch-35w">';
echo '<div class="rectangle-1-L53">';
echo '</div>';
echo '<p class="hotel-management-system-ft1">HOTEL MANAGEMENT SYSTEM</p>';
echo '<div class="rectangle-6-Ywo">';
echo '</div>';
echo '<p class="function-list-HuP">';
echo 'Function';
echo '<br/>';
echo 'list';
echo '</p>';
echo '<p class="employee-info-Bjs">';
echo 'Employee';
echo '<br/>';
echo 'Info';
echo '</p>';
echo '<p class="management-VkZ">Management</p>';
echo '<p class="reserve-and-checkout-1yo">';
echo 'Reserve';
echo '<br/>';
echo 'and';
echo '<br/>';
echo 'Checkout';
echo '</p>';
echo '<p class="room-info-management-HRX">';
echo 'Room';
echo '<br/>';
echo 'Info';
echo '<br/>';
echo 'Management';
echo '</p>';
echo '<p class="customer-info-query-bh7">';
echo 'Customer';
echo '<br/>';
echo 'Info';
echo '<br/>';
echo 'Query';
echo '</p>';
echo '<p class="change-password-JLd">';
echo 'Change';
echo '<br/>';
echo 'Password';
echo '</p>';
echo '</div>';
echo '<p class="layout-1Vw">Layout</p>';
echo '<div class="auto-group-7zp5-M41">';
echo '<div class="auto-group-tv4h-U8d">Reservation</div>';
echo '<div class="auto-group-iobb-8iy">';
echo '<div class="auto-group-cjh3-Sjf">';
echo '<img class="rectangle-5-PQ1" src="./assets/rectangle-5.png"/>';
echo '<div class="rectangle-8-K2m">';
echo '</div>';
echo '<p class="room-number-customer-name-phone-number-e-mail-current-time-note--Tem">';
echo 'Room Number:';
echo '<br/>';
echo 'Customer Name:';
echo '<br/>';
echo 'Phone Number:';
echo '<br/>';
echo 'E-mail:';
echo '<br/>';
echo 'Current Time:';
echo '<br/>';
echo 'Note:';
echo '</p>';
echo '</div>';
echo '</div>';
echo '<div class="auto-group-kzvz-LiZ">';
echo '<div class="auto-group-y8ms-4Pf">';
echo '<p class="return-QCd">Return</p>';
echo '<img class="line-14-ecm" src="./assets/line-14.png"/>';
echo '</div>';
echo '<div class="auto-group-g6to-6zZ">Reserve</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</body>';
?>